title: O Livro Azul
description: Aulas de computação e ciências exatas
theme: just-the-docs

url: https://olivroazul.com.br

aux_links:
  YouTube Channel: https://www.youtube.com/@olivroazul
aux_links_new_tab: true



